export const ErrorCode = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  REAUTHENTICATION_REQUIRED: "REAUTHENTICATION_REQUIRED",
  RATE_LIMITED: "RATE_LIMITED",
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_REDIRECT_URI: "INVALID_REDIRECT_URI",
  INVALID_PKCE: "INVALID_PKCE",
  INVALID_PROVIDER: "INVALID_PROVIDER",
  INVALID_GRANT: "INVALID_GRANT",
  LOGIN_EXPIRED: "LOGIN_EXPIRED",
  GOOGLE_NOT_CONFIGURED: "GOOGLE_NOT_CONFIGURED",
  EMAIL_NOT_CONFIGURED: "EMAIL_NOT_CONFIGURED",
  ACCOUNT_CONFLICT: "ACCOUNT_CONFLICT",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  HANDLE_INVALID: "HANDLE_INVALID",
  HANDLE_RESERVED: "HANDLE_RESERVED",
  HANDLE_TAKEN: "HANDLE_TAKEN",
  HANDLE_CONFUSABLE: "HANDLE_CONFUSABLE",
  HANDLE_COOLDOWN: "HANDLE_COOLDOWN",
  HANDLE_REQUIRED: "HANDLE_REQUIRED",
  SYNC_DENIED_KEY: "SYNC_DENIED_KEY",
  LINK_UNVERIFIED: "LINK_UNVERIFIED",
  LINK_TAKEN: "LINK_TAKEN",
  LINK_INVALID: "LINK_INVALID",
  LINK_VERIFY_FAILED: "LINK_VERIFY_FAILED",
  LINK_STORE_UNSUPPORTED: "LINK_STORE_UNSUPPORTED",
  MATCH_TOO_LARGE: "MATCH_TOO_LARGE",
  MEDIA_UNSUPPORTED: "MEDIA_UNSUPPORTED",
  MEDIA_TOO_LARGE: "MEDIA_TOO_LARGE",
  MEDIA_INVALID: "MEDIA_INVALID",
  MEDIA_DIMENSIONS_INVALID: "MEDIA_DIMENSIONS_INVALID",
  MEDIA_CONFLICT: "MEDIA_CONFLICT",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export class ApiError extends Error {
  readonly status: number;
  readonly code: ErrorCode;
  readonly retryAfterSec?: number;

  constructor(status: number, code: ErrorCode, message: string, retryAfterSec?: number) {
    super(message);
    this.status = status;
    this.code = code;
    this.retryAfterSec = retryAfterSec;
  }
}

export function errorBody(err: ApiError): { error: { code: ErrorCode; message: string } } {
  return { error: { code: err.code, message: err.message } };
}
